const mongoose = require('mongoose');
const moment = require('moment-timezone');
const timeZone = 'Asia/Bangkok';
const date = moment.tz(Date.now(), timeZone);

const mySchema = new mongoose.Schema({
    email: String,
    score: Number,
    deliverable: Boolean,
    account_details: {
        apple: Boolean,
        ebay: Boolean,
        facebook: Boolean,
        flickr: Boolean,
        foursquare: Boolean,
        github: Boolean,
        google: Boolean,
        gravatar: Boolean,
        instagram: Boolean,
        lastfm: Boolean,
        linkedin: Boolean,
        microsoft: Boolean,
        myspace: Boolean,
        pinterest: Boolean,
        skype: Boolean,
        spotify: Boolean,
        tumblr: Boolean,
        vimeo: Boolean,
        weibo: Boolean,
        yahoo: Boolean,
        discord: Boolean,
        ok: Boolean,
        kakao: Boolean,
        booking: Boolean,
        airbnb: Boolean,
        amazon: Boolean,
        qzone: Boolean,
        adobe: Boolean,
        mailru: Boolean,
        wordpress: Boolean,
        imgur: Boolean,
        disneyplus: Boolean,
        netflix: Boolean,
        jdid: Boolean,
        flipkart: Boolean,
        bukalapak: Boolean,
        archiveorg: Boolean,
        lazada: Boolean,
        zoho: Boolean,
        samsung: Boolean,
        evernote: Boolean,
        envato: Boolean,
        patreon: Boolean,
        tokopedia: Boolean,
        rambler: Boolean,
        quora: Boolean,
        atlassian: Boolean,
    },

    createdAt: {type: Date, default: date},
    updatedAt: {type: Date, default: date},
    deletedAt: {type: Date, default: null},

});
module.exports = mongoose.model('seon_email-101-200', mySchema)